name: Build and Release

on:
  push:
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always
  RELEASE_NAME: ${{ github.ref_name }}

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust (MSVC)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true

      - name: Build Release Binary
        run: cargo build --release

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ github.ref }}
          files: |
            target/release/healthcheck.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
